Maxbitmap setting

diff --git a/programs/pdf2pdfa b/programs/pdf2pdfa
--- a/programs/pdf2pdfa
+++ b/programs/pdf2pdfa
@@ -5,12 +5,22 @@ set -u
 INPUT=$1
 OUTPUT=$2
 DPI=$3
+MAXBITMAP=$4
+
 if [ -z "$DPI" ]; then
   DPI=720
 fi
 re='^[0-9]+$'
 if ! [[ $DPI =~ $re ]] ; then
   echo "error: DPI is not a number"
+  exit 2
+fi
+
+if [ -z "$MAXBITMAP" ]; then
+  MAXBITMAP=0
+fi
+if ! [[ $MAXBITMAP =~ $re ]] ; then
+  echo "error: MAXBITMAP is not a number"
   exit 2
 fi
 
@@ -24,5 +34,5 @@ docker run \
   --rm \
   laundry-programs \
     /bin/bash -c 'cat > /home/docconv/document.pdf && \
-    gs -q -dPDFA -dBATCH -dNOPAUSE -r'$DPI' -sProcessColorModel=DeviceCMYK -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=1 -sOutputFile=- /home/docconv/document.pdf' \
+    gs -q -dPDFA -dBATCH -dNOPAUSE -r'$DPI' -dMaxBitmap='$MAXBITMAP' -sProcessColorModel=DeviceCMYK -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=1 -sOutputFile=- /home/docconv/document.pdf' \
     < "$INPUT" > "$OUTPUT"
