Add pdfsettings parameter

diff --git a/programs/pdf2pdfa b/programs/pdf2pdfa
--- a/programs/pdf2pdfa
+++ b/programs/pdf2pdfa
@@ -6,6 +6,7 @@ INPUT=$1
 OUTPUT=$2
 DPI=$3
 MAXBITMAP=$4
+PDFSETTINGS=$5
 
 if [ -z "$DPI" ]; then
   DPI=720
@@ -14,6 +15,24 @@ re='^[0-9]+$'
 if ! [[ $DPI =~ $re ]] ; then
   echo "error: DPI is not a number"
   exit 2
+fi
+
+
+if [ -n "$PDFSETTINGS" ]; then
+  valid_settings=("/screen" "/ebook" "/printer" "/prepress" "/default")
+  for i in "${valid_settings[@]}"
+  do
+    if [ "$i" = "$PDFSETTINGS" ] ; then
+      found=true
+    fi
+  done
+  if [ "$found" != true ]; then
+    echo "error: Invalid PDFSETTINGS value"
+    exit 2
+  fi
+  PDFSETTINGS="-dPDFSETTINGS=$PDFSETTINGS"
+else
+  PDFSETTINGS="-dPDFSETTINGS=/default"
 fi
 
 if [ -z "$MAXBITMAP" ]; then
@@ -34,5 +53,5 @@ docker run \
   --rm \
   laundry-programs \
     /bin/bash -c 'cat > /home/docconv/document.pdf && \
-    gs -q -dPDFA -dBATCH -dNOPAUSE -r'$DPI' -dMaxBitmap='$MAXBITMAP' -sProcessColorModel=DeviceCMYK -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=1 -sOutputFile=- /home/docconv/document.pdf' \
+    gs -q -dPDFA -dBATCH -dNOPAUSE -r'$DPI' -dMaxBitmap='$MAXBITMAP' '$PDFSETTINGS' -sProcessColorModel=DeviceCMYK -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=1 -sOutputFile=- /home/docconv/document.pdf' \
     < "$INPUT" > "$OUTPUT"
