Add configuration for PDF/A conformance level

diff --git a/programs/pdf2pdfa b/programs/pdf2pdfa
--- a/programs/pdf2pdfa
+++ b/programs/pdf2pdfa
@@ -7,6 +7,7 @@ OUTPUT=$2
 DPI=$3
 MAXBITMAP=$4
 PDFSETTINGS=$5
+PDFA_CONFORMANCE=$6
 
 if [ -z "$DPI" ]; then
   DPI=720
@@ -43,6 +44,16 @@ if ! [[ $MAXBITMAP =~ $re ]] ; then
   exit 2
 fi
 
+PDFA_CONFORMANCE_NUM=""
+if [[ ! $PDFA_CONFORMANCE =~ $re ]] || [[ "$PDFA_CONFORMANCE" -lt 1 ]] || [[ "$PDFA_CONFORMANCE" -gt 3 ]]; then
+  echo "error: PDFA_CONFORMANCE invalid - only values from 1 to 3 are allowed"
+  exit 2
+fi
+if [ -n "$PDFA_CONFORMANCE" ] && [ "$PDFA_CONFORMANCE" -gt 1 ]; then
+  # The ghostscript documentation specifies that -dPDFA parameter should only have the version value followed when using 2 or 3
+  PDFA_CONFORMANCE_NUM="=$PDFA_CONFORMANCE"
+fi
+
 docker run \
   --runtime="${LAUNDRY_DOCKER_RUNTIME:-runsc}" \
   --network=none \
@@ -53,5 +64,5 @@ docker run \
   --rm \
   laundry-programs \
     /bin/bash -c 'cat > /home/docconv/document.pdf && \
-    gs -q -dPDFA -dBATCH -dNOPAUSE -r'$DPI' -dMaxBitmap='$MAXBITMAP' '$PDFSETTINGS' -sProcessColorModel=DeviceCMYK -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=1 -sOutputFile=- /home/docconv/document.pdf' \
+    gs -q -dPDFA'$PDFA_CONFORMANCE_NUM' -dBATCH -dNOPAUSE -r'$DPI' -dMaxBitmap='$MAXBITMAP' '$PDFSETTINGS' -sProcessColorModel=DeviceCMYK -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=1 -sOutputFile=- /home/docconv/document.pdf' \
     < "$INPUT" > "$OUTPUT"
